# Stable: 4 replicas of v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-stable
  namespace: lab19
spec:
  replicas: 4
  selector:
    matchLabels: { app: myapp, track: stable }
  template:
    metadata:
      labels: { app: myapp, track: stable, version: v1 }
    spec:
      containers:
      - name: app
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c","touch /tmp/ready; sleep 3600"]
        readinessProbe:
          exec: { command: ["cat","/tmp/ready"] }
          periodSeconds: 3
---
# Canary: 1 replica of v2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  namespace: lab19
spec:
  replicas: 1
  selector:
    matchLabels: { app: myapp, track: canary }
  template:
    metadata:
      labels: { app: myapp, track: canary, version: v2 }
    spec:
      containers:
      - name: app
        image: busybox:1.37
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c","touch /tmp/ready; sleep 3600"]
        readinessProbe:
          exec: { command: ["cat","/tmp/ready"] }
          periodSeconds: 3
---
# Service selects app=myapp — matches BOTH tracks
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: lab19
spec:
  selector:
    app: myapp        # NOT track — so it includes stable AND canary
  ports:
  - port: 80
    targetPort: 80
