apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: lab10
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  activeDeadlineSeconds: 120
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
          - echo "running migration"; sleep 3; echo "done"; exit 0
