apiVersion: batch/v1
kind: CronJob
metadata:
  name: ticker
  namespace: lab10
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: ticker
            image: busybox:1.36
            command: ["/bin/sh", "-c", "echo tick $(date +%T)"]
