replicaCount: 1

image:
  repository: busybox
  tag: "1.36"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

message: "hello from helm"
