apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: lab22
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'fake-app'
        static_configs:
          - targets: ['fake-app:8080']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: lab22
spec:
  replicas: 1
  selector:
    matchLabels: { app: prometheus }
  template:
    metadata:
      labels: { app: prometheus }
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.53.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"   # tell it which config to read
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus      # the ConfigMap lands here as prometheus.yml
      volumes:
        - name: config
          configMap:
            name: prom-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: lab22
spec:
  selector: { app: prometheus }
  ports:
    - port: 9090
      targetPort: 9090
