apiVersion: v1
kind: Pod
metadata: { name: liveness-exec, namespace: lab11 }
spec:
  restartPolicy: Always
  containers:
  - name: app
    image: busybox:1.36
    imagePullPolicy: IfNotPresent
    args: ["/bin/sh", "-c", "touch /tmp/healthy; sleep 3600"]
    livenessProbe:
      exec: { command: ["cat", "/tmp/healthy"] }
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
