apiVersion: v1
kind: Pod
metadata: { name: no-probe, namespace: lab11 }
spec:
  containers:
  - name: app
    image: busybox:1.36
    imagePullPolicy: IfNotPresent
    args: ["/bin/sh", "-c", "sleep 3600"]
