apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab20
spec:
  replicas: 3
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels: { app: web }
      containers:
      - name: web
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c","touch /tmp/ready; sleep 3600"]
        readinessProbe:
          exec: { command: ["cat","/tmp/ready"] }
          periodSeconds: 3
