apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: lab8
type: Opaque
stringData:
  HF_TOKEN: "hf-this-is-a-fake-token-for-lab"
  DATABASE_PASSWORD: "supersecretpassword"
  API_KEY: "sk-fake-openai-key-for-testing"
