apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-discovery-sa    # The identity your pod will run as
  namespace: lab4
  # No other fields needed. Kubernetes creates a token automatically.
