apiVersion: v1
kind: Service
metadata:
  name: db-svc          # Must match StatefulSet's serviceName field
  namespace: lab3
spec:
  clusterIP: None       # THIS is what makes it headless. No virtual IP.
                        # DNS returns the actual pod IPs instead.
                        # Required for StatefulSet stable DNS per pod.
  selector:
    app: db
  ports:
  - port: 80
    targetPort: 80
